name: Sonar Continuous Integration
env:
  DOTNET_VERSION: '8.0'                     # La versión de .NET
  SONAR_ORG: 'luis-caxi-calani'              # Nombre de la organización de SonarCloud
  SONAR_PROJECT: 'luis-caxi-calani_apibank'  # Clave del proyecto de SonarCloud

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup .NET version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Cambiar al directorio correcto donde está el archivo Bank.sln
      - name: Change directory to solution folder
        run: cd lab-2024-ii-cps-u1-04-csharp-Luis-Caxi-Calani/Bank

      - name: Restore packages
        run: dotnet restore Bank.sln

      - name: Run tests and collect coverage
        run: dotnet test --collect:"XPlat Code Coverage;Format=opencover" Bank.sln

      - name: Install SonarScanner
        run: dotnet tool install -g dotnet-sonarscanner

      - name: Run SonarCloud scan
        run: |
          dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT }}" /o:"${{ env.SONAR_ORG }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="*/**/coverage.opencover.xml" /d:sonar.qualitygate.wait=true
          dotnet build Bank.sln
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

